name: Generate Snake Animation

on:
  schedule: # Runs once a day at 1 AM UTC
    - cron: "00 11 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing to repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk/svg-only@v3
        with:
          github_user_name: mkr-infinity
          outputs: dist/snake.svg

      - name: Commit and Push Snake
        run: |
          git config user.name "mkr-infinity"
          git config user.email "mohammadkaifraja2@gmail.com"
          git add dist/snake.svg
          # Always create a commit, even if file didn't change
          git commit -m "Update snake animation" || git commit --allow-empty -m "Update snake animation"
          git push origin HEAD:output --force
