name: Generate Snake Animation

on:
  schedule: # Runs once a day at midnight UTC
    - cron: "0 1 * * *"
  workflow_dispatch: # Allow manual trigger

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write   # allow pushing to repo

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Generate Snake SVG
        uses: Platane/snk@v3
        with:
          github_user_name: mkr-infinity
          svg_out_path: dist/snake.svg

      - name: Commit and Push Snake
        uses: EndBug/add-and-commit@v9
        with:
          author_name: mkr-infinity
          author_email: mohammadkaifraja2@gmail.com
          message: "Generated snake animation"
          add: "dist/snake.svg"
          push: true
          new_branch: output
